apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      initContainers:
        - name: wait-for-mosquitto
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mosquitto-svc 1883; do echo 'Esperando mosquitto-svc...'; sleep 2; done"
            ]
      containers:
        - name: ingestor
          image: ingestor:latest
          imagePullPolicy: Never

          env:
            - name: MQTT_HOST
              value: "mosquitto-svc"
            - name: KAFKA_HOST
              value: "kafka-svc:9092"
            

---
apiVersion: v1
kind: Service
metadata:
  name: ingestor-svc
spec:
  selector:
    app: ingestor
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
